services:
  api:
    platform: linux/amd64
    build: .
    command: sh -c "./node_modules/.bin/knex migrate:latest && npm run lint && npm run doc && npm test"
    restart: always
    links:
      - postgis
    ports:
      - "2000:2000"
    environment:
      - GitSha=testing
      - POSTGRES=postgres://docker:docker@postgis:5432/gis
      - MAPBOX_TOKEN

  postgis:
    platform: linux/amd64
    image: kartoza/postgis:13.0
    restart: 'always'
    ports:
      - 5433:5432
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_MULTIPLE_EXTENSIONS="postgis","uuid-ossp"
      - DATADIR=/opt/postgres/data
