name: AWS Lambda

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Docker Layer Caching
              uses: satackey/action-docker-layer-caching@v0.0.11
              continue-on-error: true

            - name: Build Lambda
              run: |
                cd ./lambda
                ./upload-lambda.sh
